# This workflow builds, tests, and checks linting for the 1Password Python SDK.
name: Validate

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.21'

      - name: Build
        run: go build -v ./...

  # Branch-based pull request
  integration-trusted:
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    env:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - name: Branch based PR checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.21'
      - run: go test src/variable_test.go

  integration-fork:
    runs-on: ubuntu-latest
    # this job is always skipped and its status is only updated when the integration tests are permitted to run on this code
    if: github.event_name != 'pull_request' && github.event_name != 'push'
    steps:
      - uses: actions/checkout@v4